- hosts: "{{ servers }}"
  gather_facts: false
  
  tasks:
  - name: Check smartlis url
    ignore_errors: yes
    uri:
      url: http://{{ slwww_keepalived_ip }}/system/about
    register: output

  - name: Send message when url is not working
    delegate_to: "{{ delegate_to }}"
    slack:
      token: "{{ slack_token }}"
      msg: "Smartlis url not working {{ output.url }} --> {{ output.msg }}"
    when: output.failed == true
    
  - name: restart ilp service when output=failed
    win_service:
      name: SysMain
      state: restarted
    when: output.failed == true
    delegate_to: "{{ ilp_server }}"
    remote_user: "{{ delegation_user }}"
    register: service

  - name: debug
    debug:
      msg: "{{ service }}"
    
  - name: fail when url is not working
    fail:
    when: output.failed == true
