- hosts: "{{ servers }}"

  tasks:
  - name: Check ensemble service status
    win_command: powershell.exe "Get-Service -Name {{ cache_service }} | Select-Object Status | ConvertTo-Json"
    register: service_status

  - name: Send message if cache is not running
    delegate_to: "{{ delegate_to }}"
    remote_user: "{{ delegation_user }}"
    slack:
      token: "{{ slack_token }}"
      msg: "{{ ansible_hostname }} ensemble service is not working"
    when: service_status.stdout.find("4") == -1
    
  - name: Check Tomcat7 service status
    win_command: powershell.exe "Get-Service -Name Tomcat7 | Select-Object Status | ConvertTo-Json"
    register: service_status

  - name: Send message if Tomcat7 is not running
    delegate_to: "{{ delegate_to }}"
    remote_user: "{{ delegation_user }}"
    slack:
      token: "{{ slack_token }}"
      msg: "{{ ansible_hostname }} Tomcat7 service is not working"
    when: service_status.stdout.find("4") == -1
    
  - name: Check Apache2 service status
    win_command: powershell.exe "Get-Service -Name Apache2.4 | Select-Object Status | ConvertTo-Json"
    register: service_status

  - name: Send message if apache2 is not running
    delegate_to: "{{ delegate_to }}"
    remote_user: "{{ delegation_user }}"
    slack:
      token: "{{ slack_token }}"
      msg: "{{ ansible_hostname }} Apache2 service is not working"
    when: service_status.stdout.find("4") == -1
