- hosts: "{{ servers }}"
  user: smartlis
    
  tasks:
  - name: Checking postgresql service is up
    become: yes
    become_method: sudo
    command: service postgresql status
    ignore_errors: yes
    register: postgresql_status
   
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: "{{ delegate_to }}"
    slack:
      token: "{{ slack_token }}"
      msg: "{{ ansible_hostname }} postgresql service is not working"
    when: postgresql_status.stdout.find("inactive") != -1
    
  - name: Checking couchdb service is up
    become: yes
    become_method: sudo
    command: service couchdb status
    ignore_errors: yes
    register: couchdb_status
   
  - name: debug outuput to find "inactive" status on stdout
    delegate_to: "{{ delegate_to }}"
    slack:
      token: "{{ slack_token }}"
      msg: "{{ ansible_hostname }} couchdb service is not working"
    when: couchdb_status.stdout.find("inactive") != -1
