- hosts: localhost
  gather_facts: false
  
  tasks:
  - name: Check smartlis url
    ignore_errors: yes
    uri:
      url: http://{{ slwww_keepalived_ip }}/system/about
    register: output

  - name: Send message when url is not working
    delegate_to: localhost
    slack:
      token: T9N25BYMC/BEJ5TU0MP/UkjPmJsB7d1D0BAA2Belyjxf
      msg: "Smartlis url not working {{ output.url }} --> {{ output.msg }}"
    when: output.failed == true
    
  - name: restart ilp service when output=failed
    win_service:
      name: SysMain
      state: restarted
    when: output.failed == true
    delegate_to: srvwsus
    remote_user: Administrador
    register: service

  - name: debug
    debug:
      msg: "{{ service }}"
    
  - name: fail when url is not working
    fail:
    when: output.failed == true
